NUM_OF_ROWS = 30
NUM_OF_COLUMNS = 50
CELL_WIDTH = 15
CELL_HEIGHT = 15

CANVAS_CELL_TAG = "cell"
CANVAS_START_TAG = "start"
CANVAS_STOP_TAG = "stop"

GAME_STATE_PLAYING = "playing"
GAME_STATE_PAUSED = "paused"

STEP_DELAY = 100